export const USER_ROLES = {
  BEEKEEPER: 'BEEKEEPER',
  PROCESSOR: 'PROCESSOR',
  LAB: 'LAB',
  CUSTOMER: 'CUSTOMER',
  ADMIN: 'ADMIN',
  INSPECTOR: 'INSPECTOR'
};

export const BATCH_STATUS = {
  HARVESTED: 'HARVESTED',
  COLLECTED: 'COLLECTED',
  TESTING: 'TESTING',
  TESTED: 'TESTED',
  VERIFIED: 'VERIFIED',
  PROCESSING: 'PROCESSING',
  PACKAGED: 'PACKAGED',
  IN_TRANSIT: 'IN_TRANSIT',
  DELIVERED: 'DELIVERED'
};

export const CERTIFICATION_STATUS = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  EXPIRED: 'EXPIRED',
  REVOKED: 'REVOKED'
};

export const HIVE_HEALTH_STATUS = {
  HEALTHY: 'HEALTHY',
  ATTENTION_NEEDED: 'ATTENTION_NEEDED',
  WARNING: 'WARNING',
  CRITICAL: 'CRITICAL'
};
