export const USER_ROLES = {
  BEEKEEPER: 'BEEKEEPER',
  CUSTOMER: 'CUSTOMER'
};

export const BATCH_STATUS = {
  HARVESTED: 'HARVESTED',
  COLLECTED: 'COLLECTED',
  TESTING: 'TESTING',
  VERIFIED: 'VERIFIED',
  PROCESSING: 'PROCESSING',
  PACKAGED: 'PACKAGED',
  IN_TRANSIT: 'IN_TRANSIT',
  DELIVERED: 'DELIVERED'
};
