"""Part 8 Database Architecture

Revision ID: 70747f54d215
Revises: None
Create Date: 2026-09-04 11:32:35.549515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70747f54d215'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('honey_batches',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('batch_code', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('is_merged', sa.Boolean(), nullable=True),
    sa.Column('document_hash', sa.String(), nullable=True),
    sa.Column('tx_hash', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_honey_batches_batch_code'), 'honey_batches', ['batch_code'], unique=True)
    op.create_index(op.f('ix_honey_batches_created_at'), 'honey_batches', ['created_at'], unique=False)
    op.create_index(op.f('ix_honey_batches_id'), 'honey_batches', ['id'], unique=False)
    op.create_index(op.f('ix_honey_batches_status'), 'honey_batches', ['status'], unique=False)
    op.create_index(op.f('ix_honey_batches_tx_hash'), 'honey_batches', ['tx_hash'], unique=False)
    op.create_table('batch_transformations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('parent_batch_id', sa.String(), nullable=False),
    sa.Column('child_batch_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('parent_batch_id != child_batch_id', name='check_no_self_referential_transformation'),
    sa.ForeignKeyConstraint(['child_batch_id'], ['honey_batches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_batch_id'], ['honey_batches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_batch_transformations_child_batch_id'), 'batch_transformations', ['child_batch_id'], unique=False)
    op.create_index(op.f('ix_batch_transformations_created_at'), 'batch_transformations', ['created_at'], unique=False)
    op.create_index(op.f('ix_batch_transformations_id'), 'batch_transformations', ['id'], unique=False)
    op.create_index(op.f('ix_batch_transformations_parent_batch_id'), 'batch_transformations', ['parent_batch_id'], unique=False)
    op.create_index(op.f('ix_batch_transformations_type'), 'batch_transformations', ['type'], unique=False)
    op.create_table('beekeepers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('license_no', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_beekeepers_id'), 'beekeepers', ['id'], unique=False)
    op.create_index(op.f('ix_beekeepers_license_no'), 'beekeepers', ['license_no'], unique=True)
    op.create_index(op.f('ix_beekeepers_user_id'), 'beekeepers', ['user_id'], unique=True)
    op.create_table('lab_tests',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('batch_id', sa.String(), nullable=False),
    sa.Column('test_type', sa.String(), nullable=False),
    sa.Column('result', sa.String(), nullable=False),
    sa.Column('lab_name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['honey_batches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lab_tests_batch_id'), 'lab_tests', ['batch_id'], unique=False)
    op.create_index(op.f('ix_lab_tests_created_at'), 'lab_tests', ['created_at'], unique=False)
    op.create_index(op.f('ix_lab_tests_id'), 'lab_tests', ['id'], unique=False)
    op.create_table('apiaries',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('beekeeper_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('lat IS NULL OR (lat >= -90.0 AND lat <= 90.0)', name='check_lat_range'),
    sa.CheckConstraint('lng IS NULL OR (lng >= -180.0 AND lng <= 180.0)', name='check_lng_range'),
    sa.ForeignKeyConstraint(['beekeeper_id'], ['beekeepers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_apiaries_beekeeper_id'), 'apiaries', ['beekeeper_id'], unique=False)
    op.create_index(op.f('ix_apiaries_id'), 'apiaries', ['id'], unique=False)
    op.create_table('harvest_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('hive_id', sa.String(), nullable=False),
    sa.Column('beekeeper_id', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=False),
    sa.Column('tx_hash', sa.String(), nullable=True),
    sa.Column('batch_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('weight_kg > 0', name='check_harvest_quantity_positive'),
    sa.ForeignKeyConstraint(['batch_id'], ['honey_batches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['beekeeper_id'], ['beekeepers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['hive_id'], ['hives.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_harvest_events_batch_id'), 'harvest_events', ['batch_id'], unique=False)
    op.create_index(op.f('ix_harvest_events_beekeeper_id'), 'harvest_events', ['beekeeper_id'], unique=False)
    op.create_index(op.f('ix_harvest_events_hive_id'), 'harvest_events', ['hive_id'], unique=False)
    op.create_index(op.f('ix_harvest_events_id'), 'harvest_events', ['id'], unique=False)
    op.create_index(op.f('ix_harvest_events_timestamp'), 'harvest_events', ['timestamp'], unique=False)
    op.create_index(op.f('ix_harvest_events_tx_hash'), 'harvest_events', ['tx_hash'], unique=False)
    op.create_table('batch_sources',
    sa.Column('batch_id', sa.String(), nullable=False),
    sa.Column('harvest_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['honey_batches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['harvest_id'], ['harvest_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('batch_id', 'harvest_id'),
    sa.UniqueConstraint('batch_id', 'harvest_id', name='uq_batch_harvest_source')
    )
    op.create_index(op.f('ix_batch_sources_batch_id'), 'batch_sources', ['batch_id'], unique=False)
    op.create_index(op.f('ix_batch_sources_harvest_id'), 'batch_sources', ['harvest_id'], unique=False)
    op.drop_index(op.f('ix_batches_id'), table_name='batches')
    op.drop_table('batches')
    op.drop_index(op.f('ix_harvests_id'), table_name='harvests')
    op.drop_table('harvests')
    op.add_column('blockchain_transactions', sa.Column('related_table', sa.String(), nullable=False))
    op.add_column('blockchain_transactions', sa.Column('related_id', sa.String(), nullable=False))
    op.add_column('blockchain_transactions', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.alter_column('blockchain_transactions', 'tx_hash',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('blockchain_transactions', 'timestamp',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.create_index(op.f('ix_blockchain_transactions_related_id'), 'blockchain_transactions', ['related_id'], unique=False)
    op.create_index(op.f('ix_blockchain_transactions_related_table'), 'blockchain_transactions', ['related_table'], unique=False)
    op.create_index(op.f('ix_blockchain_transactions_timestamp'), 'blockchain_transactions', ['timestamp'], unique=False)
    op.drop_constraint(None, 'custody_transfers', type_='foreignkey')
    op.create_foreign_key(None, 'custody_transfers', 'honey_batches', ['batch_id'], ['id'], ondelete='CASCADE')
    op.add_column('hives', sa.Column('apiary_id', sa.String(), nullable=True))
    op.add_column('hives', sa.Column('hive_code', sa.String(), nullable=True))
    op.add_column('hives', sa.Column('install_date', sa.DateTime(), nullable=True))
    op.add_column('hives', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('hives', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.create_index(op.f('ix_hives_apiary_id'), 'hives', ['apiary_id'], unique=False)
    op.create_index(op.f('ix_hives_farm_id'), 'hives', ['farm_id'], unique=False)
    op.create_index(op.f('ix_hives_hive_code'), 'hives', ['hive_code'], unique=True)
    op.create_index(op.f('ix_hives_owner_id'), 'hives', ['owner_id'], unique=False)
    op.drop_constraint(None, 'hives', type_='foreignkey')
    op.drop_constraint(None, 'hives', type_='foreignkey')
    op.create_foreign_key(None, 'hives', 'farms', ['farm_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'hives', 'users', ['owner_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'hives', 'apiaries', ['apiary_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_ml_analyses_hive_id'), 'ml_analyses', ['hive_id'], unique=False)
    op.create_index(op.f('ix_ml_analyses_timestamp'), 'ml_analyses', ['timestamp'], unique=False)
    op.drop_constraint(None, 'ml_analyses', type_='foreignkey')
    op.create_foreign_key(None, 'ml_analyses', 'hives', ['hive_id'], ['id'], ondelete='CASCADE')
    op.add_column('products', sa.Column('product_code', sa.String(), nullable=False))
    op.add_column('products', sa.Column('bottle_date', sa.DateTime(), nullable=False))
    op.alter_column('products', 'batch_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('products', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('products', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.create_index(op.f('ix_products_product_code'), 'products', ['product_code'], unique=True)
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.create_foreign_key(None, 'products', 'honey_batches', ['batch_id'], ['id'], ondelete='CASCADE')
    op.alter_column('sensor_readings', 'hive_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('sensor_readings', 'timestamp',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.create_index('idx_sensor_readings_hive_time', 'sensor_readings', ['hive_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_sensor_readings_hive_id'), 'sensor_readings', ['hive_id'], unique=False)
    op.create_index(op.f('ix_sensor_readings_timestamp'), 'sensor_readings', ['timestamp'], unique=False)
    op.drop_constraint(None, 'sensor_readings', type_='foreignkey')
    op.create_foreign_key(None, 'sensor_readings', 'hives', ['hive_id'], ['id'], ondelete='CASCADE')
    op.add_column('users', sa.Column('name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_verification_records_batch_id'), 'verification_records', ['batch_id'], unique=False)
    op.create_index(op.f('ix_verification_records_created_at'), 'verification_records', ['created_at'], unique=False)
    op.drop_constraint(None, 'verification_records', type_='foreignkey')
    op.drop_constraint(None, 'verification_records', type_='foreignkey')
    op.create_foreign_key(None, 'verification_records', 'honey_batches', ['batch_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'verification_records', type_='foreignkey')
    op.create_foreign_key(None, 'verification_records', 'blockchain_transactions', ['tx_hash'], ['tx_hash'])
    op.create_foreign_key(None, 'verification_records', 'batches', ['batch_id'], ['id'])
    op.drop_index(op.f('ix_verification_records_created_at'), table_name='verification_records')
    op.drop_index(op.f('ix_verification_records_batch_id'), table_name='verification_records')
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'name')
    op.drop_constraint(None, 'sensor_readings', type_='foreignkey')
    op.create_foreign_key(None, 'sensor_readings', 'hives', ['hive_id'], ['id'])
    op.drop_index(op.f('ix_sensor_readings_timestamp'), table_name='sensor_readings')
    op.drop_index(op.f('ix_sensor_readings_hive_id'), table_name='sensor_readings')
    op.drop_index('idx_sensor_readings_hive_time', table_name='sensor_readings')
    op.alter_column('sensor_readings', 'timestamp',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('sensor_readings', 'hive_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.create_foreign_key(None, 'products', 'batches', ['batch_id'], ['id'])
    op.drop_index(op.f('ix_products_product_code'), table_name='products')
    op.alter_column('products', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('products', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('products', 'batch_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('products', 'bottle_date')
    op.drop_column('products', 'product_code')
    op.drop_constraint(None, 'ml_analyses', type_='foreignkey')
    op.create_foreign_key(None, 'ml_analyses', 'hives', ['hive_id'], ['id'])
    op.drop_index(op.f('ix_ml_analyses_timestamp'), table_name='ml_analyses')
    op.drop_index(op.f('ix_ml_analyses_hive_id'), table_name='ml_analyses')
    op.drop_constraint(None, 'hives', type_='foreignkey')
    op.drop_constraint(None, 'hives', type_='foreignkey')
    op.drop_constraint(None, 'hives', type_='foreignkey')
    op.create_foreign_key(None, 'hives', 'users', ['owner_id'], ['id'])
    op.create_foreign_key(None, 'hives', 'farms', ['farm_id'], ['id'])
    op.drop_index(op.f('ix_hives_owner_id'), table_name='hives')
    op.drop_index(op.f('ix_hives_hive_code'), table_name='hives')
    op.drop_index(op.f('ix_hives_farm_id'), table_name='hives')
    op.drop_index(op.f('ix_hives_apiary_id'), table_name='hives')
    op.drop_column('hives', 'updated_at')
    op.drop_column('hives', 'created_at')
    op.drop_column('hives', 'install_date')
    op.drop_column('hives', 'hive_code')
    op.drop_column('hives', 'apiary_id')
    op.drop_constraint(None, 'custody_transfers', type_='foreignkey')
    op.create_foreign_key(None, 'custody_transfers', 'batches', ['batch_id'], ['id'])
    op.drop_index(op.f('ix_blockchain_transactions_timestamp'), table_name='blockchain_transactions')
    op.drop_index(op.f('ix_blockchain_transactions_related_table'), table_name='blockchain_transactions')
    op.drop_index(op.f('ix_blockchain_transactions_related_id'), table_name='blockchain_transactions')
    op.alter_column('blockchain_transactions', 'timestamp',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('blockchain_transactions', 'tx_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('blockchain_transactions', 'created_at')
    op.drop_column('blockchain_transactions', 'related_id')
    op.drop_column('blockchain_transactions', 'related_table')
    op.create_table('harvests',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('hive_id', sa.VARCHAR(), nullable=True),
    sa.Column('weight_kg', sa.FLOAT(), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('tx_hash', sa.VARCHAR(), nullable=True),
    sa.Column('batch_id', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.ForeignKeyConstraint(['hive_id'], ['hives.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_harvests_id'), 'harvests', ['id'], unique=False)
    op.create_table('batches',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('is_merged', sa.BOOLEAN(), nullable=True),
    sa.Column('document_hash', sa.VARCHAR(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_batches_id'), 'batches', ['id'], unique=False)
    op.drop_index(op.f('ix_batch_sources_harvest_id'), table_name='batch_sources')
    op.drop_index(op.f('ix_batch_sources_batch_id'), table_name='batch_sources')
    op.drop_table('batch_sources')
    op.drop_index(op.f('ix_harvest_events_tx_hash'), table_name='harvest_events')
    op.drop_index(op.f('ix_harvest_events_timestamp'), table_name='harvest_events')
    op.drop_index(op.f('ix_harvest_events_id'), table_name='harvest_events')
    op.drop_index(op.f('ix_harvest_events_hive_id'), table_name='harvest_events')
    op.drop_index(op.f('ix_harvest_events_beekeeper_id'), table_name='harvest_events')
    op.drop_index(op.f('ix_harvest_events_batch_id'), table_name='harvest_events')
    op.drop_table('harvest_events')
    op.drop_index(op.f('ix_apiaries_id'), table_name='apiaries')
    op.drop_index(op.f('ix_apiaries_beekeeper_id'), table_name='apiaries')
    op.drop_table('apiaries')
    op.drop_index(op.f('ix_lab_tests_id'), table_name='lab_tests')
    op.drop_index(op.f('ix_lab_tests_created_at'), table_name='lab_tests')
    op.drop_index(op.f('ix_lab_tests_batch_id'), table_name='lab_tests')
    op.drop_table('lab_tests')
    op.drop_index(op.f('ix_beekeepers_user_id'), table_name='beekeepers')
    op.drop_index(op.f('ix_beekeepers_license_no'), table_name='beekeepers')
    op.drop_index(op.f('ix_beekeepers_id'), table_name='beekeepers')
    op.drop_table('beekeepers')
    op.drop_index(op.f('ix_batch_transformations_type'), table_name='batch_transformations')
    op.drop_index(op.f('ix_batch_transformations_parent_batch_id'), table_name='batch_transformations')
    op.drop_index(op.f('ix_batch_transformations_id'), table_name='batch_transformations')
    op.drop_index(op.f('ix_batch_transformations_created_at'), table_name='batch_transformations')
    op.drop_index(op.f('ix_batch_transformations_child_batch_id'), table_name='batch_transformations')
    op.drop_table('batch_transformations')
    op.drop_index(op.f('ix_honey_batches_tx_hash'), table_name='honey_batches')
    op.drop_index(op.f('ix_honey_batches_status'), table_name='honey_batches')
    op.drop_index(op.f('ix_honey_batches_id'), table_name='honey_batches')
    op.drop_index(op.f('ix_honey_batches_created_at'), table_name='honey_batches')
    op.drop_index(op.f('ix_honey_batches_batch_code'), table_name='honey_batches')
    op.drop_table('honey_batches')
    # ### end Alembic commands ###
